name: 'byu-oit/github-action-package-json'
description: 'Parses and outputs information from a package.json file'
author: 'Brigham Young University'
inputs:
  version:
    required: false
    description: 'Toggles the version module to output version information.'
outputs:
  version:
    description: 'A rich version object which includes the version, major, minor, patch, build, and prerelease properties from the Semver class in the semver module (see semver/functions/parse for more information).'
runs:
  using: 'node16'
  main: 'dist/index.js'
